#!/bin/bash

MYTOOLS=~/myTools

# My scripts
PATH=$PATH:$MYTOOLS/bin

# My prompt
PS1="\[\033[35m\]\T \D{%p}\[\033[m\] \[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h\[\033[m\]:\[\033[34;1m\]\w\[\033[m\]\$ "

# Source my awesome aliases
for f in ~/.bash_aliases*; do source $f; done

# Python CLI
export PYTHONSTARTUP=~/.pythonrc
# My python tools
export PYTHONPATH=$PYTHONPATH:$MYTOOLS/python

# Bash preferences
HISTSIZE=100000
HISTIGNORE="ls:ps:history"
