#!/bin/bash

MYTOOLS=~/myTools

PATH=$PATH:$MYTOOLS/bin

# Source my awesome aliases
for f in ~/.bash_aliases*; do source $f; done

# Python CLI
export PYTHONSTARTUP=~/.pythonrc
# My python tools
export PYTHONPATH=$PYTHONPATH:$MYTOOLS/python

# Bash preferences
HISTSIZE=100000
HISTIGNORE="ls:ps:history"
