#!/bin/bash

for f in ~/.bash_aliases*; do source $f; done

export PYTHONSTARTUP=~/.pythonrc

# source Virtualenvwrapper
if [ -f /usr/bin/virtualenvwrapper.sh ]; then
    source /usr/bin/virtualenvwrapper.sh
fi
if [ -f ~/.local/bin/virtualenvwrapper.sh ]; then
    source ~/.local/bin/virtualenvwrapper.sh
fi
